name: skating_game
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.10.1
  flame_tiled: ^1.16.0
  flame_audio: ^2.1.2
  onepref: ^0.0.14
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/images/Tilemap/
    - assets/images/HUD/
    - assets/images/Background/
    - assets/tiles/

